#!/usr/bin/env python3

"""
  ___  __    ____  ____
 / __)(  )  (_  _)(  _ \
( (_-. )(__  _)(_  )(_) )
 \___/(____)(____)(____/
"""

from __future__ import print_function
import sys
from lib import help as glid_help
from lib import install as glid_install

if len(sys.argv) < 2:
    print ("No arguments given try *glid help*")
    sys.exit()
if sys.argv[1] == "help":
    glid_help.main()
elif sys.argv[1] == "install":
    if len(sys.argv) < 3:
        glid_install.main()
    else:
        glid_install.pre_install(sys.argv[2:])
else:
    print ("Unkown agument try *glid help*")
